### ISSUE TITLE
Show more info for credentials related failure (e.g. missing password, etc)

### ISSUE THREAD

**Issue by bhamail** [sonatype-nexus-community/cargo-pants#61]
While configuring for use with IQ, I was seeing errors like those below:

```
...
 🦀 Obtained package list (148)
 🦀 SBOM generated
 ❌ Error generating Nexus IQ Server results
error decoding response body: expected value at line 1 column 1
```
with the log showing:
```
{"timestamp":"2021-11-16T16:52:23.802917Z","level":"ERROR","fields":{"message":"error decoding response body: expected value at line 1 column 1"},"target":"cargo_iq"}
```

There was no clear indication (at least not clear to me) that the cause of the failure was I had forgotten to add the `--iq-token` parameter. I think it would be helpful if the error message for this sort of failure gave more help stating the true cause of the failure (e.g. credentials).

**Comment by bhamail** [comment]
More info: Here's a call trace of a permissions related failure:

```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', src/iq.rs:310:29
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   2: core::panicking::panic_bounds_check
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:77:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/slice/index.rs:184:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/slice/index.rs:15:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/alloc/src/vec/mod.rs:2465:9
   6: cargo_pants::iq::IQClient::audit_with_iq_server
             at ./src/iq.rs:310:29
   7: cargo_iq::main
             at ./src/bin/iq/main.rs:103:27
   8: core::ops::function::FnOnce::call_once
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227:5
```
